volumes:
  mailpit:

services:
  pocketbase:
    build: .
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PB_ENCRYPTION_KEY=${PB_ENCRYPTION_KEY:-4yXEsvw66m98RqKSPQKJWYoe4juKGWZM}
    volumes:
      - ./pb/data:/pb/pb_data
      - ./pb/hooks:/pb/pb_hooks
      - ./pb/migrations:/pb/pb_migrations
      - ./dev:/development
    entrypoint: /development/start.sh

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - mailpit:/data
      - ./dev:/development
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: true
      MP_SMTP_AUTH_ALLOW_INSECURE: true
      MP_SMTP_TLS_KEY: /development/key.pem
      MP_SMTP_TLS_CERT: /development/cert.pem
