/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as AuthLoginImport } from "./routes/auth.login";
import { Route as AuthEmailVerifyImport } from "./routes/auth.email-verify";

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const AuthLoginRoute = AuthLoginImport.update({
  path: "/auth/login",
  getParentRoute: () => rootRoute,
} as any);

const AuthEmailVerifyRoute = AuthEmailVerifyImport.update({
  path: "/auth/email-verify",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/auth/email-verify": {
      id: "/auth/email-verify";
      path: "/auth/email-verify";
      fullPath: "/auth/email-verify";
      preLoaderRoute: typeof AuthEmailVerifyImport;
      parentRoute: typeof rootRoute;
    };
    "/auth/login": {
      id: "/auth/login";
      path: "/auth/login";
      fullPath: "/auth/login";
      preLoaderRoute: typeof AuthLoginImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AuthEmailVerifyRoute,
  AuthLoginRoute,
});

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/email-verify",
        "/auth/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth/email-verify": {
      "filePath": "auth.email-verify.tsx"
    },
    "/auth/login": {
      "filePath": "auth.login.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
